/**
 * Parses a delimited multi-file project format generated by the AI.
 *
 * files[] is the SINGLE source of truth. Both code mode and preview
 * derive from these files. The preview is built at runtime by an
 * in-iframe Babel + module loader (see project-runtime-preview.tsx).
 *
 * Format:
 * ===PROJECT_MANIFEST===
 * { "type": "project", "framework": "...", ... }
 * ===END_MANIFEST===
 * ===FILE:path/to/file.tsx===
 * file content here
 * ===END_FILE===
 *
 * NOTE: ===PREVIEW_HTML=== is no longer generated. Legacy artifacts
 * may still contain it; getPreviewHtml() exists only as a backward-
 * compatibility fallback for those records.
 */

export type ProjectFile = {
  path: string;
  content: string;
  language: string;
};

export type ProjectAsset = {
  path: string;
  kind: "image";
  source: "generated" | "fallback" | "uploaded";
  prompt?: string;
  url: string;
};

export type ProjectMeta = {
  type: "project";
  framework: string;
  title?: string;
  summary?: string;
  entryFile?: string;
  previewEntryFile?: string;
  siteType?: string;
  designFamily?: string;
  designDirection?: string;
  colorStrategy?: string;
  typography?: string;
  sectionOrder?: string[];
};

export type ParsedProject = {
  meta: ProjectMeta | null;
  files: ProjectFile[];
  assets: ProjectAsset[];
  previewHtml: string | null;
  isComplete: boolean;
};

function inferLanguage(path: string): string {
  if (path.endsWith(".tsx")) return "tsx";
  if (path.endsWith(".ts")) return "typescript";
  if (path.endsWith(".jsx")) return "jsx";
  if (path.endsWith(".js")) return "javascript";
  if (path.endsWith(".css")) return "css";
  if (path.endsWith(".html")) return "html";
  if (path.endsWith(".json")) return "json";
  if (path.endsWith(".md")) return "markdown";
  return "text";
}

export function isProjectContent(content: string): boolean {
  return content.includes("===PROJECT_MANIFEST===") || content.includes("===FILE:");
}

export function parseProjectContent(raw: string): ParsedProject {
  const files: ProjectFile[] = [];
  const assets: ProjectAsset[] = [];

  // Extract completed files
  const fileRegex = /===FILE:(.*?)===\n([\s\S]*?)===END_FILE===/g;
  let match: RegExpExecArray | null;
  while ((match = fileRegex.exec(raw)) !== null) {
    const path = match[1].trim();
    files.push({
      path,
      content: match[2].trimEnd(),
      language: inferLanguage(path),
    });
  }

  // Extract preview HTML if complete
  const previewMatch = raw.match(
    /===PREVIEW_HTML===\n([\s\S]*?)===END_PREVIEW===/
  );
  const previewHtml = previewMatch ? previewMatch[1].trimEnd() : null;

  // Extract manifest if complete
  const manifestMatch = raw.match(
    /===PROJECT_MANIFEST===\n([\s\S]*?)===END_MANIFEST===/
  );
  let meta: ProjectMeta | null = null;
  if (manifestMatch) {
    try {
      meta = JSON.parse(manifestMatch[1].trim());
    } catch {
      // Manifest might be malformed during streaming
      meta = null;
    }
  }

  // Extract assets from manifest or files
  if (meta && "assets" in meta) {
    const rawAssets = (meta as Record<string, unknown>).assets;
    if (Array.isArray(rawAssets)) {
      for (const a of rawAssets) {
        if (a && typeof a === "object" && "path" in a && "url" in a) {
          assets.push(a as ProjectAsset);
        }
      }
    }
  }

  // Determine completeness — files[] is the source of truth.
  // PREVIEW_HTML is no longer required.
  const hasManifest = manifestMatch !== null;
  const isComplete = hasManifest && files.length > 0;

  return { meta, files, assets, previewHtml, isComplete };
}

/**
 * Returns the number of completed files found so far (for streaming progress).
 */
export function countCompletedFiles(raw: string): number {
  const matches = raw.match(/===END_FILE===/g);
  return matches ? matches.length : 0;
}

/**
 * Checks if a file is currently being streamed (started but not ended).
 */
export function getCurrentStreamingFile(raw: string): string | null {
  const lastFileStart = raw.lastIndexOf("===FILE:");
  if (lastFileStart === -1) return null;

  const afterStart = raw.slice(lastFileStart);
  if (afterStart.includes("===END_FILE===")) return null;

  const nameMatch = afterStart.match(/===FILE:(.*?)===/);
  return nameMatch ? nameMatch[1].trim() : null;
}

/**
 * Backward-compatibility fallback for legacy artifacts that contain
 * a PREVIEW_HTML section. New generations no longer produce this.
 * Preview should derive from files[] via the runtime renderer.
 */
export function getPreviewHtml(raw: string): string | null {
  const match = raw.match(/===PREVIEW_HTML===\n([\s\S]*?)===END_PREVIEW===/);
  return match ? match[1].trimEnd() : null;
}
